export const ENDPOINTS = {
  DONATIONS: '/donations',
  DONATION_BY_ID: (id) => `/donations/${id}`,
  DONATION_SEND_RECEIPT: (id) => `/donations/${id}/send-receipt`,
  DONATIONS_SEND_RECEIPTS: '/donations/send-receipts',
  DONATIONS_MARK_SENT: '/donations/mark-sent',
  DONORS: '/donors',
  DONOR_BY_ID: (id) => `/donors/${id}`,
  DONOR_UPSERT_BY_EMAIL: '/donors/upsert-by-email',
  DASHBOARD_SUMMARY: '/dashboard/summary',
  DASHBOARD_TREND: '/dashboard/trend',
  DASHBOARD_LAST6: '/dashboard/last6months',
  DASHBOARD_RANGE_SUMMARY: '/dashboard/range-summary',
  DASHBOARD_RANGE_TREND: '/dashboard/range-trend',
  AUTH_SIGNUP: '/auth/signup',
  AUTH_TOKEN: '/auth/token',
  AUTH_ME: '/auth/me',
  AUTH_USERS: '/auth/users',
  AUTH_SET_ROLE: (uid) => `/auth/users/${uid}/role`,
  SYNC_STRIPE: '/sync/stripe/trigger',
  SYNC_STRIPE_LAST: '/sync/stripe/last',
};
